### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by intellizone** [jmrplens/A-Lab#5]
Check for missing argument or incorrect argument data type in call to function 'getRunningApp'.

Error in ALab (line 513)
            runningApp = getRunningApp(app);

Error in ALabApp/startApp (line 86)
                obj.AppHandle = eval('ALab');

Error in ALabApp (line 48)
            startApp(obj)

Error in appinstall.internal.runapp>execute (line 116)
out = evalin('caller', [script ';']);

Error in appinstall.internal.runapp>runapp13a (line 95)
outobj = execute(fullfile(appinstalldir, [wrapperfile 'App.m']));

Error in appinstall.internal.runapp>preamble18b (line 60)
    appobj = runapp13a(appinstalldir);

Error in appinstall.internal.runapp (line 13)
    out = preamble18b(appinstalldir);

Error in matlab.apputil.run (line 45)
appinstall.internal.runapp(appName, appLocation);

**Comment by jmrplens** [comment]
I could not reproduce the problem. Everything works correctly.
I need more information: Matlab version, Operating system, etc.

Please use the template to report errors. Include all the information you can offer, and skip the rest.

> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **File project**
> If applicable, add file project (.alab) to have more data to replicate the problem.
> 
> **Desktop (please complete the following information):**
>  - OS: [e.g. Windows 10]
>  - MATLAB Version [e.g. 2021a]
> 
> **Additional context**
> Add any other context about the problem here.
